Added invoice items
opsway/zohobooks-api pull request #16
Opened 2017-01-12 18:19 UTC by ppicatto

| Q             | A
| ------------- | ---
| Branch	| master
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR	| n/a

2017-01-16 20:55 UTC, phansys requested changes
Status: Needs work.

2017-01-16 20:55 UTC, phansys commented on src/Api/InvoiceItems.php
> +     * @link https://www.zoho.com/books/api/v3/settings/items/#mark-item-as-active.
Please, use `@see` instead.

2017-01-16 20:55 UTC, phansys commented on src/Api/InvoiceItems.php
> +     * @return boolean
Please, use `bool` instead.

2017-01-18 22:57 UTC, phansys approved these changes

2017-01-18 23:11 UTC, shandyDev commented
Maybe make sense create new namespace "Settings"? Looks like in zoho documentation:
![default](https://cloud.githubusercontent.com/assets/633883/22086872/9e7472d0-dde3-11e6-9abf-8009ea89ea2f.png)

So it will be:
```php
namespace OpsWay\ZohoBooks\Api\Settings;

class InvoiceItems extends BaseApi {}
// Or even just Items for class name???
class Items extends BaseApi {}
```

What you think?

2017-01-19 00:20 UTC, mrVrAlex approved these changes

2017-01-19 00:22 UTC, merged